### post test add Attendee PVJ9
POST http://localhost:8080/api/v1/attendees
Accept: application/json
Content-Type: application/json

{
  "name": "John Doe",
  "personalCode": "PVJ9"
}

### post test add Attendee PVJ8
POST http://localhost:8080/api/v1/attendees
Accept: application/json
Content-Type: application/json

{
  "name": "Janik Sinner",
  "personalCode": "CCDD"
}

### post test add Attendee PVJ7
POST http://localhost:8080/api/v1/attendees
Accept: application/json
Content-Type: application/json

{
  "name": "Nick",
  "personalCode": "PVJ7"
}

### post test Event Party Time
POST http://localhost:8080/api/v1/events
Accept: application/json
Content-Type: application/json

{
  "name": "Party time",
  "date": "2025-03-22 12:00:00",
  "attendees": [
    "PVJ9",
    "PVJ8",
    "PVJ7"
  ]
}


### post test Event Second Event
POST http://localhost:8080/api/v1/events
Accept: application/json
Content-Type: application/json

{
  "name": "Party time",
  "date": "2025-06-15 12:00:00",
  "attendees": [
    "AABB",
    "BBCC",
    "CCDD"
  ]
}

### get Attendee PVJ9
GET http://localhost:8080/api/v1/attendees/PVJ9
Accept: application/json
